FROM python:3.12-slim

WORKDIR /training
COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt
COPY training ./training
COPY models ./models

ENTRYPOINT ["python", "-m", "training.train_models"]
